AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM config for the cookbook-backend

Parameters:
  MaxRCUs:
    Type: Number
    Default: 10
  
  MaxWCUs:
    Type: Number
    Default: 10

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        USERS_DB_NAME: !Ref cookbookUsers
        LONG_TERM_AUTH_DB_NAME: !Ref cookbookLongTermAuth
        LONG_TERM_AUTH_DB_INDEX_NAME: cookbook_long_term_auth_index
        SHORT_TERM_AUTH_DB_NAME: !Ref cookbookShortTermAuth
        SHORT_TERM_AUTH_DB_INDEX_NAME: cookbook_short_term_auth_index
        PROFILE_PICTURE_S3_BUCKET_NAME: !Ref profilePicturesBucket
        PROFILE_PICTURE_CLOUDFRONT_BASE_URL: !Sub "https://${profilePicturesDistribution.DomainName}"
        NODE_OPTIONS: --enable-source-maps

Resources:
  #
  # APIGateway
  #
  CookbookHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - "https://cookbook.tylerbartschi.com"
          - "http://localhost:5173"
        AllowMethods:
          - GET
          - POST
          - PATCH
          - OPTIONS
        AllowHeaders:
          - content-type
          - authorization
        MaxAge: 600


  #
  # Lambdas
  #

  # Auth endpoints

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/auth/LoginHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookLongTermAuth
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
      Events:
        LoginRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /auth/login
            Method: POST
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/LoginHandler.ts
  
  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/auth/LogoutHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookLongTermAuth
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
      Events:
        LogoutRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /auth/logout
            Method: POST
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/LogoutHandler.ts

  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/auth/RegisterHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookLongTermAuth
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:TransactWriteItems
              Resource: !GetAtt cookbookUsers.Arn
        - S3CrudPolicy:
            BucketName: !Ref profilePicturesBucket
      Events:
        RegisterRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /auth/register
            Method: POST
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/RegisterHandler.ts
    
  SessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/auth/SessionHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookLongTermAuth
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
      Events:
        SessionRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /auth/session
            Method: GET
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/SessionHandler.ts

  UpdatePasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/auth/UpdatePasswordHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookLongTermAuth
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
      Events:
        UpdatePasswordRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /auth/update-password
            Method: POST
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/auth/UpdatePasswordHandler.ts
  
  # User endpoints

  GetPublicUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/user/GetPublicUserHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
      Events:
        GetPublicUserRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /user/{type}/{id}
            Method: GET
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/user/GetPublicUserHandler.ts

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/user/GetUserHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
      Events:
        GetUserRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /user/me
            Method: GET
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/user/GetUserHandler.ts

  UpdateEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/user/UpdateEmailHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:TransactWriteItems
              Resource: !GetAtt cookbookUsers.Arn
      Events:
        UpdateEmailRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /user/me/email
            Method: PATCH
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/user/UpdateEmailHandler.ts
  
  UpdateProfilePictureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/user/UpdateProfilePictureHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
        - S3CrudPolicy:
            BucketName: !Ref profilePicturesBucket
      Events:
        UpdateProfilePictureRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /user/me/profile-picture
            Method: PATCH
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/user/UpdateProfilePictureHandler.ts

  UpdateUsernameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/user/UpdateUsernameHandler.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookUsers
        - DynamoDBCrudPolicy:
            TableName: !Ref cookbookShortTermAuth
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:TransactWriteItems
              Resource: !GetAtt cookbookUsers.Arn
      Events:
        UpdateUsernameRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref CookbookHttpApi
            Path: /user/me/username
            Method: PATCH
            PayloadFormatVersion: "2.0"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: es2022
        Sourcemap: true
        EntryPoints:
          - src/handlers/user/UpdateUsernameHandler.ts

  #
  # S3 Buckets
  #
  profilePicturesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cookbook-profile-pictures-bartschi
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  #
  # Profile Picture CloudFront Stuff
  #
  profilePicturesOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-profile-pictures-oac"
        Description: Access control for cookbook profile pictures S3 bucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  profilePicturesDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub "${AWS::StackName} profile picture distribution"
        HttpVersion: http2and3
        PriceClass: PriceClass_100

        Origins:
          - Id: ProfilePicturesS3Origin
            DomainName: !GetAtt profilePicturesBucket.RegionalDomainName
            OriginAccessControlId: !Ref profilePicturesOAC
            S3OriginConfig:
              OriginAccessIdentity: ""
        
        DefaultCacheBehavior:
          TargetOriginId: ProfilePicturesS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
  
  profilePicturesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref profilePicturesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontServicePrincipalReadOnly
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub "${profilePicturesBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${profilePicturesDistribution}"

  #
  # DynamoDB Tables
  #
  cookbookUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cookbook_users

      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: !Ref MaxRCUs
        MaxWriteRequestUnits: !Ref MaxWCUs

      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
    

  cookbookLongTermAuth:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cookbook_long_term_auth

      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: !Ref MaxRCUs
        MaxWriteRequestUnits: !Ref MaxWCUs
      
      AttributeDefinitions:
        - AttributeName: token_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: token_id
          KeyType: HASH

      TimeToLiveSpecification:
        AttributeName: ttl_at
        Enabled: true
      
      GlobalSecondaryIndexes:
        - IndexName: cookbook_long_term_auth_index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          OnDemandThroughput:
            MaxReadRequestUnits: !Ref MaxRCUs
            MaxWriteRequestUnits: !Ref MaxWCUs

  cookbookShortTermAuth:
    Type: AWS::DynamoDB::Table
    DependsOn: cookbookLongTermAuth
    Properties:
      TableName: cookbook_short_term_auth

      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: !Ref MaxRCUs
        MaxWriteRequestUnits: !Ref MaxWCUs
      
      AttributeDefinitions:
        - AttributeName: token_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: token_id
          KeyType: HASH
      
      TimeToLiveSpecification:
        AttributeName: ttl_at
        Enabled: true
      
      GlobalSecondaryIndexes:
        - IndexName: cookbook_short_term_auth_index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          OnDemandThroughput:
            MaxReadRequestUnits: !Ref MaxRCUs
            MaxWriteRequestUnits: !Ref MaxWCUs

Outputs:
  ApiBaseUrl:
    Value: !Sub "https://${CookbookHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/prod"
  
  ProfilePicturesCloudFrontBaseUrl:
    Value: !Sub "https://${profilePicturesDistribution.DomainName}"
